In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [46]:
ls = [f'PCA {i+1}' for i in range(100)]
df = pd.read_csv('SimpsonTrain.csv')
m, n = df.shape
x_train = df.iloc[:, 1:]
y_train = df.iloc[:, 0]

In [3]:
x_train

Pixel 1  Pixel 2  Pixel 3  Pixel 4  Pixel 5  Pixel 6  Pixel 7  Pixel 8  \
0         131      120      126      124      121      124      124      123   
1          60       59       62       59       59       62       58       58   
2          59       57      106      103      100      103      109      105   
3         134      137      139      140      140      142      143      143   
4          34       61       50       62       62       58       65       65   
...       ...      ...      ...      ...      ...      ...      ...      ...   
7995      133      138      130      148      159      144       93      196   
7996      153      148      150      149      147      150      152      152   
7997       51       61      172      146      123      170      166      113   
7998      123      123      124      122      124      123      124      116   
7999       51       48       32       35       29       31       24       24   

      Pixel 9  Pixel 10  ...  Pixel 775  Pixel 776  Pixel 777  Pixel 778  \
0         123       124  ...         14         19         43        165   
1          59        56  ...         52         57         54         52   
2         107       104  ...         79         72         75         74   
3         144       139  ...        146        146        154         89   
4          63        65  ...         75         75         74         74   
...       ...       ...  ...        ...        ...        ...        ...   
7995      144       116  ...         40         40         39         38   
7996      149       152  ...         53         52         52         53   
7997      124       131  ...         91         86         91         92   
7998      122       125  ...         90         95         91         87   
7999      146       158  ...        109        112        109        116   

      Pixel 779  Pixel 780  Pixel 781  Pixel 782  Pixel 783  Pixel 784  
0           176         17         46         69         61         20  
1            54         55         54         53         52         53  
2            71         75         73         73         74         75  
3            88        123        146        148        149        148  
4            73         73         73         74         74         74  
...         ...        ...        ...        ...        ...        ...  
7995         39         41         37         37         39         41  
7996         56         57         55         54         58         55  
7997         90         93        101         66         51         53  
7998         90         98         85         71        103        100  
7999        118        115        101        110        112        115  

[8000 rows x 784 columns]

In [4]:
scaler = StandardScaler()
x_train = pd.DataFrame(scaler.fit_transform(x_train))

In [5]:
x_train

0         1         2         3         4         5         6    \
0     0.593313  0.385916  0.492631  0.468840  0.403408  0.442674  0.447134   
1    -0.732427 -0.754555 -0.714533 -0.767252 -0.766239 -0.727885 -0.805807   
2    -0.751099 -0.791948  0.115393  0.069487  0.007237  0.046195  0.162375   
3     0.649330  0.703753  0.737836  0.773109  0.761849  0.782514  0.807829   
4    -1.217909 -0.717163 -0.940876 -0.710201 -0.709644 -0.803405 -0.672920   
...        ...       ...       ...       ...       ...       ...       ...   
7995  0.630658  0.722449  0.568079  0.925243  1.120289  0.820274 -0.141369   
7996  1.004106  0.909412  0.945318  0.944260  0.893905  0.933554  0.978685   
7997 -0.900479 -0.717163  1.360280  0.887210  0.441139  1.311154  1.244460   
7998  0.443934  0.442005  0.454907  0.430807  0.460004  0.423794  0.447134   
7999 -0.900479 -0.960214 -1.280391 -1.223655 -1.332198 -1.313165 -1.451262   

           7         8         9    ...       774       775       776  \
0     0.435740  0.438848  0.461306  ... -1.588812 -1.504296 -1.034454   
1    -0.802245 -0.775595 -0.840250  ... -0.878277 -0.788532 -0.825372   
2     0.092913  0.135237  0.078495  ... -0.373423 -0.505993 -0.426215   
3     0.816658  0.837337  0.748413  ...  0.879362  0.887863  1.075377   
4    -0.668924 -0.699692 -0.667985  ... -0.448217 -0.449486 -0.445222   
...        ...       ...       ...  ...       ...       ...       ...   
7995  1.826093  0.837337  0.308182  ... -1.102657 -1.108742 -1.110484   
7996  0.988072  0.932216  0.997240  ... -0.859579 -0.882711 -0.863387   
7997  0.245281  0.457824  0.595289  ... -0.149044 -0.242291 -0.122095   
7998  0.302418  0.419872  0.480446  ... -0.167742 -0.072768 -0.122095   
7999 -1.449807  0.875289  1.112083  ...  0.187525  0.247442  0.220040   

           777       778       779       780       781       782       783  
0     1.295055  1.538302 -1.532899 -0.959145 -0.508317 -0.661972 -1.444735  
1    -0.857350 -0.820082 -0.796065 -0.803887 -0.820668 -0.835468 -0.810631  
2    -0.438298 -0.491455 -0.408257 -0.435151 -0.430229 -0.411367 -0.387894  
3    -0.152580 -0.162828  0.522481  0.981575  1.033916  1.034435  1.014822  
4    -0.438298 -0.452793 -0.447038 -0.435151 -0.410707 -0.411367 -0.407110  
...        ...       ...       ...       ...       ...       ...       ...  
7995 -1.124019 -1.110047 -1.067530 -1.133810 -1.133019 -1.086074 -1.041214  
7996 -0.838302 -0.781420 -0.757284 -0.784480 -0.801146 -0.719804 -0.772200  
7997 -0.095437 -0.124166 -0.059230  0.108251 -0.566883 -0.854746 -0.810631  
7998 -0.190676 -0.124166  0.037722 -0.202264 -0.469273  0.147677  0.092488  
7999  0.361711  0.417103  0.367358  0.108251  0.292082  0.321173  0.380717  

[8000 rows x 784 columns]

In [6]:
pca = PCA(n_components=100)
pca.fit(x_train)
data_pca = pca.transform(x_train)
data_pca = pd.DataFrame(data_pca, columns=ls)

In [7]:
data_pca

PCA 1      PCA 2      PCA 3     PCA 4     PCA 5     PCA 6     PCA 7  \
0      9.977573  13.545765   2.366761 -2.854556 -2.841486  1.077622 -2.688534   
1    -17.851645  -1.864787   6.205749 -1.092097  1.320488 -4.960201  4.680704   
2     -7.418017  -6.526185   2.995566  2.794544 -1.810756 -5.173121  4.340692   
3     10.909341   3.969711  -2.544792  4.640243 -2.934724  2.475461 -2.666907   
4     -6.579641  -0.850654   1.420914 -1.112052  5.703691 -4.695223 -1.244286   
...         ...        ...        ...       ...       ...       ...       ...   
7995  -1.605518  13.894255   5.126779 -0.341710 -4.781397 -6.599710 -0.882753   
7996   3.923827  10.657055  -3.112319 -5.884876 -2.816065  0.991868  2.976934   
7997  -5.373448  -4.990798   6.275130 -3.279237 -1.685087  3.829746 -2.405120   
7998   9.652586   4.815105  -2.860540 -3.985831  3.410269  4.171436 -3.353448   
7999   3.344914  -2.228213 -13.370786 -7.397103 -6.538537 -0.981246 -0.889731   

         PCA 8     PCA 9    PCA 10  ...    PCA 91    PCA 92    PCA 93  \
0     0.617396 -6.446157  4.560164  ...  0.440823  0.369339  0.211814   
1     0.461940  1.412957 -1.435517  ...  0.433336  0.581795  1.084731   
2     4.464236  2.635041  1.241684  ... -1.076881 -0.161997 -0.153009   
3    -0.059361  1.658440 -0.624194  ...  0.042507  0.090596 -1.089111   
4    -2.447744  2.146342 -0.544198  ...  0.482066  1.298820 -0.436902   
...        ...       ...       ...  ...       ...       ...       ...   
7995  4.849546  6.739145  4.089738  ...  1.279890  0.404677 -0.807504   
7996  1.242645 -1.731573  2.914176  ...  0.020896  0.902999  0.054121   
7997  3.814336  7.089509  3.622361  ... -0.776980 -0.591944 -0.359966   
7998 -0.250048  1.874514 -0.786525  ...  0.348552  0.356818  0.106200   
7999 -8.788383 -2.785137  1.433527  ... -1.216080 -1.131081  0.544956   

        PCA 94    PCA 95    PCA 96    PCA 97    PCA 98    PCA 99   PCA 100  
0    -1.368433 -0.120222  1.229054 -0.285720  1.203904 -0.451358 -1.563230  
1     0.342252  0.274818 -0.761700  0.241110  0.309010 -0.711600  1.588901  
2     0.000913 -0.154683 -0.160878  0.129895 -0.644804 -0.301356 -0.168844  
3     0.535249 -0.478186 -0.813299  0.753674 -0.144853 -1.062029 -0.614318  
4     0.448579 -0.378870  0.308274  0.283836  1.619902  0.131347 -0.775405  
...        ...       ...       ...       ...       ...       ...       ...  
7995  0.170312  0.962817 -0.173065  1.450927 -0.384632  0.368479 -1.908786  
7996  0.243631 -0.735045 -0.681684  0.067877  0.803923  1.066647 -0.404455  
7997  0.512754 -0.003767  0.766045 -0.920838 -1.196477 -1.067547  0.206585  
7998 -0.795807  0.379580  0.372999  0.409014  0.457049 -0.274366 -0.166166  
7999 -0.413136  0.042567 -0.341745 -0.331221 -0.099483  1.734020  0.182514  

[8000 rows x 100 columns]

In [8]:
data_pca = np.array(data_pca)
y_train = df.iloc[:, 0]
y_train = np.array(y_train)
data_pca = data_pca.T
y_train = y_train.T

In [9]:
x_train.shape

(8000, 784)

In [10]:
data_pca.shape

(100, 8000)

In [17]:
def init_params():
    W1 = np.random.rand(128, 100) - 0.5
    b1 = np.random.rand(128, 1) - 0.5
    W2 = np.random.rand(64, 128) - 0.5
    b2 = np.random.rand(64, 1) - 0.5
    W3 = np.random.rand(10, 64) - 0.5
    b3 = np.random.rand(10, 1) - 0.5
    return W1, b1, W2, b2, W3, b3

def ReLU(Z):
    return np.maximum(Z, 0)

def softmax(Z):
    A = np.exp(Z) / sum(np.exp(Z))
    return A

def forward_prop(W1, b1, W2, b2, W3, b3, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = ReLU(Z2)
    Z3 = W3.dot(A2) + b3
    A3 = softmax(Z3)

    return Z1, A1, Z2, A2, Z3, A3

def ReLU_deriv(Z):
    return Z > 0

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def backward_prop(Z1, A1, Z2, A2, Z3, A3, W1, W2, W3, X, Y):
    one_hot_Y = one_hot(Y)
    dZ3 = A3 - one_hot_Y
    dW3 = 1 / m * dZ3.dot(A2.T)
    db3 = 1 / m * np.sum(dZ3)
    dZ2 = W3.T.dot(dZ3) * ReLU_deriv(Z2)
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * ReLU_deriv(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2, dW3, db3

def update_params(W1, b1, W2, b2, W3, b3, dW1, db1, dW2, db2, dW3, db3, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1
    W2 = W2 - alpha * dW2
    b2 = b2 - alpha * db2
    W3 = W3 - alpha * dW3
    b3 = b3 - alpha * db3
    return W1, b1, W2, b2, W3, b3

In [18]:
def get_predictions(A3):
    return np.argmax(A3, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2, W3, b3 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2, Z3, A3 = forward_prop(W1, b1, W2, b2, W3, b3, X)
        dW1, db1, dW2, db2, dW3, db3 = backward_prop(Z1, A1, Z2, A2, Z3, A3, W1, W2, W3, X, Y)
        W1, b1, W2, b2, W3, b3 = update_params(W1, b1, W2, b2, W3, b3, dW1, db1, dW2, db2, dW3, db3, alpha)
        if i % 1000 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A3)
            print(get_accuracy(predictions, Y))
    return W1, b1, W2, b2, W3, b3

In [19]:
W1, b1, W2, b2, W3, b3 = gradient_descent(data_pca, y_train, 0.10, 20000)

Iteration:  0
[3 8 8 ... 8 8 8] [0 0 0 ... 9 9 9]
0.092875
Iteration:  1000
[3 9 2 ... 9 4 9] [0 0 0 ... 9 9 9]
0.4
Iteration:  2000
[7 9 2 ... 9 4 9] [0 0 0 ... 9 9 9]
0.501375
Iteration:  3000
[7 9 2 ... 9 4 9] [0 0 0 ... 9 9 9]
0.57025
Iteration:  4000
[0 9 2 ... 9 4 9] [0 0 0 ... 9 9 9]
0.626
Iteration:  5000
[0 9 2 ... 9 4 9] [0 0 0 ... 9 9 9]
0.662
Iteration:  6000
[0 9 2 ... 9 4 9] [0 0 0 ... 9 9 9]
0.694875
Iteration:  7000
[0 9 2 ... 9 4 9] [0 0 0 ... 9 9 9]
0.719625
Iteration:  8000
[0 9 2 ... 9 3 9] [0 0 0 ... 9 9 9]
0.7415
Iteration:  9000
[0 5 3 ... 9 3 9] [0 0 0 ... 9 9 9]
0.76125
Iteration:  10000
[0 5 3 ... 9 3 9] [0 0 0 ... 9 9 9]
0.77075
Iteration:  11000
[0 5 0 ... 9 3 9] [0 0 0 ... 9 9 9]
0.784625
Iteration:  12000
[0 5 0 ... 9 3 9] [0 0 0 ... 9 9 9]
0.79525
Iteration:  13000
[0 0 0 ... 9 3 9] [0 0 0 ... 9 9 9]
0.804875
Iteration:  14000
[0 0 0 ... 9 3 9] [0 0 0 ... 9 9 9]
0.813125
Iteration:  15000
[0 0 0 ... 9 3 9] [0 0 0 ... 9 9 9]
0.82075
Iteration:  16000
[0 0 

In [32]:
def make_predictions(X, W1, b1, W2, b2, W3, b3):
    _, _, _, _, _, A3 = forward_prop(W1, b1, W2, b2, W3, b3, X)
    predictions = get_predictions(A3)
    return predictions

In [40]:
ds = pd.read_csv('SimpsonTest.csv')
x_test = ds.iloc[:, 1:]
y_test = ds.iloc[:, 0]
x_test = pd.DataFrame(scaler.fit_transform(x_test))
y_test = np.array(y_test)
y_test = y_test.T

In [41]:
pca.fit(x_test)
test_pca = pca.transform(x_test)
test_pca = pd.DataFrame(test_pca, columns=ls)

In [42]:
test_pca

PCA 1      PCA 2     PCA 3      PCA 4     PCA 5     PCA 6     PCA 7  \
0     11.798957  -4.197567 -2.073875   3.156806  0.721919 -0.913983  0.751670   
1      0.741402   9.728059 -1.321390  -2.702550  3.123788 -3.905426 -1.375052   
2      5.463929   2.977254  3.238968  -1.511527  1.216049  2.820762  3.258105   
3     -4.628582  -9.405482 -0.296879   0.676427  1.739246 -6.383127 -0.795502   
4    -10.526118   3.691886  3.884735   5.293686  6.739408 -2.324555 -8.356165   
...         ...        ...       ...        ...       ...       ...       ...   
1995   2.462159 -15.481563 -1.172269  12.014050 -6.329311  3.591672  5.742472   
1996 -28.780508   5.106584  1.594941   7.116821 -3.878193 -1.111233 -0.016152   
1997 -16.960171  -0.893332  4.901374   1.405955  0.095659  6.126287 -3.357307   
1998  -6.093304 -13.362445 -2.389809   2.960104 -0.829137 -1.283735  0.672186   
1999  22.063387   4.075776  1.241871  -1.890155 -5.187353 -5.487341 -3.836198   

         PCA 8      PCA 9     PCA 10  ...    PCA 91    PCA 92    PCA 93  \
0     0.620962   0.784239   1.754010  ...  0.068385  1.142517  0.485666   
1     6.384071   1.182284  -1.390001  ...  0.001928 -0.765071  0.156776   
2    -3.208041   1.227934   0.176648  ...  0.424717  0.087334  0.178863   
3     5.178291  -3.968409  -4.821685  ... -0.751709  1.026167  0.605478   
4    -3.350540   0.009375   9.162938  ... -0.133610  1.051646 -2.847627   
...        ...        ...        ...  ...       ...       ...       ...   
1995 -4.774093   5.116467  10.687023  ... -0.798100 -1.903015  0.290922   
1996 -1.202516   4.036610   2.612250  ... -0.180193  0.150478  0.370925   
1997 -9.766658   3.648686   0.493393  ... -1.060106 -0.431822 -0.688337   
1998 -2.362805  -5.651475   4.633558  ...  0.152206  1.062184  1.298270   
1999  1.711093  12.865905   3.028404  ...  0.604594 -0.540861  0.684919   

        PCA 94    PCA 95    PCA 96    PCA 97    PCA 98    PCA 99   PCA 100  
0     0.657789  0.758461  0.633080 -0.850731  0.398037 -0.364131  0.307750  
1     0.399206  0.122250 -0.198714 -0.164049 -0.209075 -0.801175  1.184665  
2    -0.152036 -0.003252 -0.316146  1.687780  0.871365  0.391134 -1.253318  
3    -1.233444  0.266406 -0.614229  1.058262 -0.851220  2.221344 -0.339391  
4     1.601196 -0.140275  1.203613  0.230692 -1.257920  1.757754  1.167654  
...        ...       ...       ...       ...       ...       ...       ...  
1995 -1.112920 -0.159701  0.877122  0.312762 -0.071349  0.478933  0.630067  
1996 -0.206295  0.505289 -0.291670  0.038105  0.553115 -0.225616 -0.080641  
1997  0.588887 -0.127406 -0.319251  0.017641 -0.308719  0.247532  1.033944  
1998  0.623067  0.014463  0.591519  0.444771 -1.015569  0.090589 -0.103032  
1999 -0.171843  1.209462 -0.357933  0.348084 -0.551428 -0.173387 -0.601796  

[2000 rows x 100 columns]

In [43]:
test_pca = np.array(test_pca)
test_pca = test_pca.T

In [44]:
y_test

array([0, 0, 0, ..., 9, 9, 9])